repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.3
  hooks:
  - id: ruff
    args: [--fix]
  - id: ruff-format
- repo: https://github.com/adrienverge/yamllint
  rev: v1.35.1
  hooks:
  - id: yamllint
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix, --line-width=120]
