[project]
dependencies = ["ruamel.yaml"]
name = "check_gha_pinning"
requires-python = ">= 3.10"
version = "1"

[project.scripts]
check-gha-pinning = "check_gha_pinning:main"

[tool.ruff]
line-length = 120
